---
  jtr_config:
    path: "/mnt/c/github/JohnTheRipper/run/john"
    main_pot_file: "/mnt/c/research/cmiyc/2023/john.pot"
    additional_pot_files:
      - /mnt/c/github/JohnTheRipper/run/john.pot
  
  hashcat_config:
    path: "/mnt/c/github/Hashcat/hashcat"
    main_pot_file: "/mnt/c/research/cmiyc/2023/hashcat.potfile"
    additional_pot_files:
      - /mnt/c/github/hashcat/Hashcat.potfile
  
  session_management:
    main_cracked_list: "/mnt/c/research/cmiyc/2023/cracked_list.pot"

  challenge_files:
    street_team:
      file: "/mnt/c/research/cmiyc/2023/cmiyc_2023_01_street.yaml"
      format: "cmiyc_2023"

  score_info:
    bcrypt: 16777215
    sha256crypt: 720000
    sha1crypt: 430000
    md5crypt: 65000
    ssha512: 1400
    ssha: 190
    raw-sha256: 8
    raw-sha1: 3
    raw-md5: 1